// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRequest struct {
	Partitions           []string `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	StartTs              uint64   `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs                uint64   `protobuf:"varint,3,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	Count                uint64   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Offset               uint64   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Forward              bool     `protobuf:"varint,6,opt,name=forward,proto3" json:"forward,omitempty"`
	Query                string   `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (m *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(m, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetPartitions() []string {
	if m != nil {
		return m.Partitions
	}
	return nil
}

func (m *QueryRequest) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *QueryRequest) GetEndTs() uint64 {
	if m != nil {
		return m.EndTs
	}
	return 0
}

func (m *QueryRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryRequest) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

func (m *QueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type QueryResponse struct {
	Lines                []*LogLine `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetLines() []*LogLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

type LogLine struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Ts                   uint64   `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	App                  string   `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogLine) Reset()         { *m = LogLine{} }
func (m *LogLine) String() string { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()    {}
func (*LogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *LogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLine.Unmarshal(m, b)
}
func (m *LogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLine.Marshal(b, m, deterministic)
}
func (m *LogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLine.Merge(m, src)
}
func (m *LogLine) XXX_Size() int {
	return xxx_messageInfo_LogLine.Size(m)
}
func (m *LogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLine.DiscardUnknown(m)
}

var xxx_messageInfo_LogLine proto.InternalMessageInfo

func (m *LogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *LogLine) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *LogLine) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

type PartitionResponse struct {
	Partitions           []string `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionResponse) Reset()         { *m = PartitionResponse{} }
func (m *PartitionResponse) String() string { return proto.CompactTextString(m) }
func (*PartitionResponse) ProtoMessage()    {}
func (*PartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionResponse.Unmarshal(m, b)
}
func (m *PartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionResponse.Marshal(b, m, deterministic)
}
func (m *PartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionResponse.Merge(m, src)
}
func (m *PartitionResponse) XXX_Size() int {
	return xxx_messageInfo_PartitionResponse.Size(m)
}
func (m *PartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionResponse proto.InternalMessageInfo

func (m *PartitionResponse) GetPartitions() []string {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type PartitionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartitionRequest) Reset()         { *m = PartitionRequest{} }
func (m *PartitionRequest) String() string { return proto.CompactTextString(m) }
func (*PartitionRequest) ProtoMessage()    {}
func (*PartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartitionRequest.Unmarshal(m, b)
}
func (m *PartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartitionRequest.Marshal(b, m, deterministic)
}
func (m *PartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartitionRequest.Merge(m, src)
}
func (m *PartitionRequest) XXX_Size() int {
	return xxx_messageInfo_PartitionRequest.Size(m)
}
func (m *PartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartitionRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryRequest)(nil), "api.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "api.QueryResponse")
	proto.RegisterType((*LogLine)(nil), "api.LogLine")
	proto.RegisterType((*PartitionResponse)(nil), "api.PartitionResponse")
	proto.RegisterType((*PartitionRequest)(nil), "api.PartitionRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0xd7, 0xe4, 0x1f, 0x99, 0x65, 0x57, 0x30, 0x5a, 0x90, 0x97, 0x43, 0x15, 0xf9, 0x94,
	0x13, 0xa2, 0x70, 0xae, 0xfa, 0x02, 0x1c, 0xa8, 0xc5, 0xbd, 0x72, 0x8b, 0x69, 0x2d, 0x21, 0xdb,
	0xc4, 0x4e, 0xab, 0x3e, 0x54, 0x5f, 0xa1, 0xcf, 0x56, 0xc5, 0x01, 0x1a, 0x71, 0x69, 0x6f, 0xfe,
	0x7e, 0x93, 0x99, 0xf9, 0x66, 0x26, 0x90, 0x0b, 0xab, 0x66, 0xb6, 0x32, 0xde, 0x60, 0x24, 0xac,
	0x62, 0x1f, 0x04, 0x06, 0x77, 0xb5, 0xac, 0xde, 0xb8, 0x3c, 0xd4, 0xd2, 0x79, 0xbc, 0x02, 0xb0,
	0xa2, 0xf2, 0xca, 0x2b, 0xa3, 0x1d, 0x25, 0x45, 0x54, 0xe6, 0xbc, 0x43, 0xf0, 0x3f, 0xf4, 0x9d,
	0x17, 0x95, 0xbf, 0xf7, 0x8e, 0xf6, 0x0a, 0x52, 0xc6, 0x3c, 0x0b, 0x7a, 0xe3, 0x70, 0x0c, 0xa9,
	0xd4, 0xdb, 0x26, 0x10, 0x85, 0x40, 0x22, 0xf5, 0x76, 0xe3, 0xf0, 0x1f, 0x24, 0x8f, 0xa6, 0xd6,
	0x9e, 0xc6, 0x2d, 0x0d, 0x02, 0x27, 0x90, 0x9a, 0xdd, 0xce, 0x49, 0x4f, 0x93, 0x80, 0x8f, 0x0a,
	0x29, 0x64, 0x3b, 0x53, 0xbd, 0x8a, 0x6a, 0x4b, 0xd3, 0x82, 0x94, 0x7d, 0x7e, 0x92, 0x4d, 0x9d,
	0x43, 0xe3, 0x94, 0x66, 0x05, 0x29, 0x73, 0xde, 0x0a, 0xb6, 0x84, 0x3f, 0x47, 0xff, 0xce, 0x1a,
	0xed, 0x24, 0x32, 0x48, 0xf6, 0x4a, 0xcb, 0xd6, 0xfb, 0xef, 0xc5, 0x60, 0xd6, 0x4c, 0xbc, 0x32,
	0x4f, 0x2b, 0xa5, 0x25, 0x6f, 0x43, 0xec, 0x16, 0xb2, 0x23, 0x41, 0x84, 0xb8, 0x61, 0x94, 0x84,
	0xa2, 0xe1, 0x8d, 0x7f, 0xa1, 0x77, 0x9e, 0xae, 0xe7, 0x1d, 0x0e, 0x21, 0x12, 0xd6, 0x86, 0xa9,
	0x72, 0xde, 0x3c, 0xd9, 0x12, 0x46, 0xeb, 0xd3, 0x4e, 0xce, 0x9d, 0xbf, 0x59, 0x1d, 0x43, 0x18,
	0x76, 0x92, 0xc2, 0xba, 0x17, 0xef, 0x04, 0xb2, 0xb5, 0xf0, 0xcf, 0xea, 0xa5, 0xc6, 0x6b, 0x88,
	0x37, 0x42, 0xed, 0x71, 0x14, 0x2c, 0x77, 0xaf, 0x32, 0xc5, 0x2e, 0x6a, 0xdb, 0xb1, 0x5f, 0x73,
	0x82, 0x73, 0x48, 0x02, 0xfc, 0x71, 0x0e, 0xde, 0x00, 0xac, 0xbf, 0xae, 0x39, 0x0e, 0xdf, 0x5c,
	0xba, 0x9a, 0x4e, 0x2e, 0xf1, 0x29, 0xfd, 0x21, 0x0d, 0xff, 0xce, 0xf2, 0x33, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x65, 0x3e, 0xc1, 0x48, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PathivuClient is the client API for Pathivu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PathivuClient interface {
	// Tail
	Tail(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Pathivu_TailClient, error)
	// Query
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Partitions
	Partitions(ctx context.Context, in *PartitionRequest, opts ...grpc.CallOption) (*PartitionResponse, error)
}

type pathivuClient struct {
	cc *grpc.ClientConn
}

func NewPathivuClient(cc *grpc.ClientConn) PathivuClient {
	return &pathivuClient{cc}
}

func (c *pathivuClient) Tail(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (Pathivu_TailClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pathivu_serviceDesc.Streams[0], "/api.Pathivu/Tail", opts...)
	if err != nil {
		return nil, err
	}
	x := &pathivuTailClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Pathivu_TailClient interface {
	Recv() (*QueryResponse, error)
	grpc.ClientStream
}

type pathivuTailClient struct {
	grpc.ClientStream
}

func (x *pathivuTailClient) Recv() (*QueryResponse, error) {
	m := new(QueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pathivuClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/api.Pathivu/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pathivuClient) Partitions(ctx context.Context, in *PartitionRequest, opts ...grpc.CallOption) (*PartitionResponse, error) {
	out := new(PartitionResponse)
	err := c.cc.Invoke(ctx, "/api.Pathivu/Partitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PathivuServer is the server API for Pathivu service.
type PathivuServer interface {
	// Tail
	Tail(*QueryRequest, Pathivu_TailServer) error
	// Query
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Partitions
	Partitions(context.Context, *PartitionRequest) (*PartitionResponse, error)
}

// UnimplementedPathivuServer can be embedded to have forward compatible implementations.
type UnimplementedPathivuServer struct {
}

func (*UnimplementedPathivuServer) Tail(req *QueryRequest, srv Pathivu_TailServer) error {
	return status.Errorf(codes.Unimplemented, "method Tail not implemented")
}
func (*UnimplementedPathivuServer) Query(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedPathivuServer) Partitions(ctx context.Context, req *PartitionRequest) (*PartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Partitions not implemented")
}

func RegisterPathivuServer(s *grpc.Server, srv PathivuServer) {
	s.RegisterService(&_Pathivu_serviceDesc, srv)
}

func _Pathivu_Tail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PathivuServer).Tail(m, &pathivuTailServer{stream})
}

type Pathivu_TailServer interface {
	Send(*QueryResponse) error
	grpc.ServerStream
}

type pathivuTailServer struct {
	grpc.ServerStream
}

func (x *pathivuTailServer) Send(m *QueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Pathivu_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathivuServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Pathivu/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathivuServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pathivu_Partitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PathivuServer).Partitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Pathivu/Partitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PathivuServer).Partitions(ctx, req.(*PartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pathivu_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Pathivu",
	HandlerType: (*PathivuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _Pathivu_Query_Handler,
		},
		{
			MethodName: "Partitions",
			Handler:    _Pathivu_Partitions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tail",
			Handler:       _Pathivu_Tail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
