# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.QueryRequest" do
    repeated :partitions, :string, 1
    optional :start_ts, :uint64, 2
    optional :end_ts, :uint64, 3
    optional :count, :uint64, 4
    optional :offset, :uint64, 5
    optional :forward, :bool, 6
    optional :query, :string, 7
  end
  add_message "api.QueryResponse" do
    repeated :lines, :message, 1, "api.LogLine"
    optional :json, :string, 2
  end
  add_message "api.LogLine" do
    optional :inner, :string, 1
    optional :ts, :uint64, 2
    optional :app, :string, 3
    optional :structured, :bool, 4
  end
  add_message "api.PartitionResponse" do
    repeated :partitions, :string, 1
  end
  add_message "api.Empty" do
  end
  add_message "api.PushLogLine" do
    optional :ts, :uint64, 1
    repeated :indexes, :string, 2
    optional :structured, :bool, 3
    optional :raw_data, :bytes, 4
    repeated :json_keys, :string, 5
  end
  add_message "api.PushRequest" do
    optional :source, :string, 1
    repeated :lines, :message, 2, "api.PushLogLine"
  end
end

module Api
  QueryRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.QueryRequest").msgclass
  QueryResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.QueryResponse").msgclass
  LogLine = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.LogLine").msgclass
  PartitionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.PartitionResponse").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Empty").msgclass
  PushLogLine = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.PushLogLine").msgclass
  PushRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.PushRequest").msgclass
end
